"""LLM backends for synthetic dataset generation.

The dataset generator is backend-agnostic: any callable that turns a
`(system, user)` prompt pair into an answer string works. This module ships
three implementations:

  - `StubBackend`    — deterministic canned answer per region (for tests + CI)
  - `OllamaBackend`  — calls our local Ollama server (Gemma 4 31B by default)
  - `AnthropicBackend` — calls the Anthropic Messages API (Claude)

Pick via `--backend` on the generator CLI. The stub is used by tests and
quickly produces a complete dataset shape so the pipeline can be exercised
end-to-end without any model calls.
"""
from __future__ import annotations

import os
from typing import Protocol


class LLMBackend(Protocol):
    """Anything that turns (system, user) into a string answer."""

    name: str

    def generate(self, system: str, user: str) -> str: ...


# ---------------------------------------------------------------------------
# Stub
# ---------------------------------------------------------------------------

class StubBackend:
    """A deterministic backend for tests and CI runs.

    Returns a templated, region-aware sentence so the dataset is structurally
    valid but obviously synthetic. Never used for real fine-tunes.
    """

    name = "stub"

    def generate(self, system: str, user: str) -> str:
        # The user prompt always names the region in parentheses, e.g. "in
        # Primary Visual Cortex (V1)". Pull it for a slightly tailored stub.
        marker = " ("
        end = user.find(")")
        if marker in user and end > 0:
            start = user.rindex(marker, 0, end) + len(marker)
            abbr = user[start:end]
        else:
            abbr = "?"
        return (
            f"[stub answer] The activation pattern in {abbr} reflects its "
            f"canonical role; full reasoning is generated by a real backend "
            f"in production runs."
        )


# ---------------------------------------------------------------------------
# Ollama (local Gemma 4 31B by default)
# ---------------------------------------------------------------------------

class OllamaBackend:
    """Generate against our local Ollama server.

    Defaults to `gemma4:31b` — the largest, most capable Gemma 4. The 5090
    has VRAM headroom for it (~21 GB) when TRIBE is unloaded. For speed at
    the cost of quality, pass `model="gemma4:e4b"`.
    """

    def __init__(
        self,
        model: str = "gemma4:31b",
        url: str | None = None,
        temperature: float = 0.4,
        num_predict: int = 600,
    ) -> None:
        self.model = model
        self.name = f"ollama:{model}"
        self.temperature = temperature
        self.num_predict = num_predict
        # Defer importing cortex.config until use to keep this module testable
        if url is None:
            url = os.environ.get("OLLAMA_URL", "http://localhost:11434")
        self.url = url.rstrip("/")

    def generate(self, system: str, user: str) -> str:
        # Lazy import so a missing `requests` install doesn't break stub tests.
        import requests

        resp = requests.post(
            f"{self.url}/api/generate",
            json={
                "model": self.model,
                "system": system,
                "prompt": user,
                "stream": False,
                "think": False,
                "options": {
                    "temperature": self.temperature,
                    "num_predict": self.num_predict,
                    "num_ctx": 8192,
                },
                "keep_alive": "10m",
            },
            timeout=300,
        )
        resp.raise_for_status()
        return resp.json().get("response", "").strip()


# ---------------------------------------------------------------------------
# Anthropic (Claude)
# ---------------------------------------------------------------------------

class AnthropicBackend:
    """Generate against Anthropic's Messages API.

    The hackathon spec lists Claude as one option for synthetic dataset
    generation. We use Sonnet by default for cost balance; for the highest
    quality, pass `model="claude-opus-4-7"`.

    Requires `ANTHROPIC_API_KEY` in the environment and the `anthropic` SDK
    installed (not in the default cortex deps — install via
    `pip install anthropic`).
    """

    def __init__(
        self,
        model: str = "claude-sonnet-4-7",
        max_tokens: int = 1200,
        temperature: float = 0.5,
    ) -> None:
        self.model = model
        self.name = f"anthropic:{model}"
        self.max_tokens = max_tokens
        self.temperature = temperature

    def generate(self, system: str, user: str) -> str:
        # Lazy import so the rest of the pipeline runs without `anthropic`.
        try:
            import anthropic  # type: ignore[import-not-found]
        except ImportError as exc:
            raise RuntimeError(
                "AnthropicBackend requires the `anthropic` package. "
                "Install with: pip install anthropic"
            ) from exc

        client = anthropic.Anthropic()
        message = client.messages.create(
            model=self.model,
            max_tokens=self.max_tokens,
            temperature=self.temperature,
            system=system,
            messages=[{"role": "user", "content": user}],
        )
        # The Anthropic SDK returns a list of content blocks; for simple text
        # responses we just concatenate the text parts.
        chunks = []
        for block in message.content:
            if getattr(block, "type", None) == "text":
                chunks.append(block.text)
            elif isinstance(block, dict) and block.get("type") == "text":
                chunks.append(block.get("text", ""))
        return "\n".join(chunks).strip()


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

def make_backend(spec: str) -> LLMBackend:
    """Parse a backend spec string into a backend instance.

    Accepts:
      "stub"
      "ollama"                  → gemma4:31b
      "ollama:gemma4:e4b"       → that model
      "anthropic"               → claude-sonnet-4-7
      "anthropic:claude-opus-4-7"
    """
    if spec == "stub":
        return StubBackend()
    if spec == "ollama":
        return OllamaBackend()
    if spec.startswith("ollama:"):
        return OllamaBackend(model=spec.removeprefix("ollama:"))
    if spec == "anthropic":
        return AnthropicBackend()
    if spec.startswith("anthropic:"):
        return AnthropicBackend(model=spec.removeprefix("anthropic:"))
    raise ValueError(
        f"Unknown backend: {spec!r}. Valid: stub, ollama, ollama:<model>, "
        "anthropic, anthropic:<model>."
    )


__all__ = [
    "AnthropicBackend",
    "LLMBackend",
    "OllamaBackend",
    "StubBackend",
    "make_backend",
]
